spring:
  datasource:
    url: jdbc:hsqldb:mem:requestFormDB
    driver-class-name: org.hsqldb.jdbcDriver
    username: SA
    password: SA
  jpa:
    generate-ddl: true
  hibernate:
    ddl-auto: create
  flyway:
    baseline-on-migrate: true